# Problem 4

*ek 4 and 4 ka indentity matrixs banao and uka ndim check karo*

In [6]:
import numpy as np
idenitity_matrixs = np.eye(4,dtype='int32')
print(idenitity_matrixs.ndim)
print(idenitity_matrixs.dtype)
print(idenitity_matrixs)

2
int32
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
