## Problem 5

*ek 6 and 6 ka mtrixs banao and uske numbers (1 to 36) and uske akhiri row and akhrir col ko pritn karo*

In [3]:
import numpy as np
array = np.arange(1,37).reshape(6,6)
print("last row of this array : ",array[-1])
print("last col of this array : ",array[:,-1])
print("\n")
print(array)
print(array.ndim)
print(array.shape)
print(array.size)

last row of this array :  [31 32 33 34 35 36]
last col of this array :  [ 6 12 18 24 30 36]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
2
(6, 6)
36
