## Problem 6 

*ussi 6 and 6 array ke bich se 2 and 2 ka sub array nikal lo*

In [4]:
import numpy as np
matrixs = np.arange(1,37)
reshape_matrixs = matrixs.reshape(6,6)
print(reshape_matrixs)

print("\n")

print(reshape_matrixs[2:4,2:4])
print(reshape_matrixs[2:4])
print(reshape_matrixs[:,2:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[[15 16]
 [21 22]]
[[13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]]
