## Problem 10

*`seed(10)` set kar ke do bar random array genrate karo*

In [10]:
import numpy as np
np.random.seed(10)
random_array = np.random.randint(1,17,(4,4))
print(random_array)

[[10 14  5 16]
 [ 1  2 12 13]
 [10 14  1 14]
 [ 2 11  9 10]]
