# 01_Foundation_Of_NumPy

In [1]:
import numpy as np

### 1. ndArray creating array


`Scalar` : 0D  array

`Vector` : 1D array

`matrixs` : 2D matrixs

In [ ]:
# single element is this array or np 
# 0D array
nd_signle_array = np.array(1)
print("signle nd array one element only allow in:",nd_signle_array)
print("type of nd 0D array : ", type(nd_signle_array))


print("\n")


# 1D array
# multiple element is this list 
nd_array = np.array([1,2,3])
print("array : ",nd_array)
print("type of nd 1D array : ", type(nd_array))


print("\n")


# 1D array
# multiple element is this list 
nd_array2 = np.array((1,2,3,4))
print("array 2 using tuple : ",nd_array2)
print("type of 1D array : ", type(nd_array2))



print("\n")



# 2D array
# multiple array in one array 
array_2d= np.array([[1,2,3],[4,5,6]])   # [1,2,3,4,5,6] instead of [[1,2,3] , [4,5,6]]
print("2D array : ", array_2d)
print("type of 2d array : ", type(array_2d))


print("\n")


# 3D array
array_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3d array : \n",array_3d)





signle nd array one element only allow in: 1
type of nd 0D array :  <class 'numpy.ndarray'>


array :  [1 2 3]
type of nd 1D array :  <class 'numpy.ndarray'>


array 2 using tuple :  [1 2 3 4]
type of 1D array :  <class 'numpy.ndarray'>


2D array :  [[1 2 3]
 [4 5 6]]
type of 2d array :  <class 'numpy.ndarray'>


3d array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. shape , ndim , size in NumPy

*Concept:*

`shape` → dimensions

`ndim` → number of axes

`size` → total elements

In [28]:
arrays = np.array([[1,2,3],[4,5,6],[2,1,2]])  
print("Array  : \n", arrays)

print("array row and col : ",arrays.shape)  # row and col batata hai 
print("array  demensial : ", arrays.ndim)  # kitne dem ka ye matrixs hai [[ ]] 2d hai agr three baracets hota to [[[ ]]] 3D dem ka hota 
print("array size : ",arrays.size) # yaha array me kitne element hai ye bata hai

Array  : 
 [[1 2 3]
 [4 5 6]
 [2 1 2]]
array row and col :  (3, 3)
array  demensial :  2
array size :  9


### 3. dtype_system of array

In [36]:
arrays = np.array([[1,2,3,4],[2,"A",2,3]])
print(arrays.shape)

print(arrays.dtype)


arrays_1 = np.array([1,2,3])
print(arrays_1.dtype)

arrays_2 = np.array([1,2,3.02])
print(arrays_2.dtype)

(2, 4)
<U21
int64
float64
