# 01_Foundation_Of_NumPy

In [1]:
import numpy as np

### 1. ndArray creating array


`Scalar` : 0D  array

`Vector` : 1D array

`matrixs` : 2D matrixs

In [ ]:
# single element is this array or np 
# 0D array
nd_signle_array = np.array(1)
print("signle nd array one element only allow in:",nd_signle_array)
print("type of nd 0D array : ", type(nd_signle_array))


print("\n")


# 1D array
# multiple element is this list 
nd_array = np.array([1,2,3])
print("array : ",nd_array)
print("type of nd 1D array : ", type(nd_array))


print("\n")


# 1D array
# multiple element is this list 
nd_array2 = np.array((1,2,3,4))
print("array 2 using tuple : ",nd_array2)
print("type of 1D array : ", type(nd_array2))



print("\n")



# 2D array
# multiple array in one array 
array_2d= np.array([[1,2,3],[4,5,6]])   # [1,2,3,4,5,6] instead of [[1,2,3] , [4,5,6]]
print("2D array : ", array_2d)
print("type of 2d array : ", type(array_2d))


print("\n")


# 3D array
array_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3d array : \n",array_3d)





signle nd array one element only allow in: 1
type of nd 0D array :  <class 'numpy.ndarray'>


array :  [1 2 3]
type of nd 1D array :  <class 'numpy.ndarray'>


array 2 using tuple :  [1 2 3 4]
type of 1D array :  <class 'numpy.ndarray'>


2D array :  [[1 2 3]
 [4 5 6]]
type of 2d array :  <class 'numpy.ndarray'>


3d array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. shape , ndim , size in NumPy

*Concept:*

`shape` → dimensions

`ndim` → number of axes

`size` → total elements

In [28]:
arrays = np.array([[1,2,3],[4,5,6],[2,1,2]])  
print("Array  : \n", arrays)

print("array row and col : ",arrays.shape)  # row and col batata hai 
print("array  demensial : ", arrays.ndim)  # kitne dem ka ye matrixs hai [[ ]] 2d hai agr three baracets hota to [[[ ]]] 3D dem ka hota 
print("array size : ",arrays.size) # yaha array me kitne element hai ye bata hai

Array  : 
 [[1 2 3]
 [4 5 6]
 [2 1 2]]
array row and col :  (3, 3)
array  demensial :  2
array size :  9


### 3. dtype_system of array

In [36]:
arrays = np.array([[1,2,3,4],[2,"A",2,3]])
print(arrays.shape)

print(arrays.dtype)


arrays_1 = np.array([1,2,3])
print(arrays_1.dtype)

arrays_2 = np.array([1,2,3.02])
print(arrays_2.dtype)

(2, 4)
<U21
int64
float64


# 4. Array creation

In [ ]:
zero_matrixs = np.zeros((3,3))  # row and col define karte hai tuples me 
print("Zero array : ",zero_matrixs)

ones_matrixs = np.ones((2,2)) # row and col define karte hai tuples me 
print("ones array : ",ones_matrixs)


full_matrixs = np.full((3,3),7) # kitne row and col chaiye wo dete hai and uske baad konsa number array me rakhna hai wo dete hai jise isme 7 diyagaya hai
print("full matrixses : ",full_matrixs)



# identity matrixs 
eyes_matrixs = np.eye(3)
print("eyes matrixs  : ",eyes_matrixs)


arange_matrixs = np.arange(0,10,2)
print("a range matrixs : ",arange_matrixs)


linspace_matrixs = np.linspace(0,10,5)
print("linspace matrixs : ",linspace_matrixs)


matrixs = np.linspace(0,10,11)
print(matrixs)


print("\n")

random_martixs = np.random.random((2,3))
print(random_martixs)

print("\n")

rand_martixs = np.random.rand(2,3)
print(rand_martixs)


randient_martixs = np.random.randint(0,10,(3,3))
print(randient_martixs)



Zero array :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array :  [[1. 1.]
 [1. 1.]]
full matrixses :  [[7 7 7]
 [7 7 7]
 [7 7 7]]
eyes matrixs  :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
a range matrixs :  [0 2 4 6 8]
linspace matrixs :  [ 0.   2.5  5.   7.5 10. ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


[[0.32937985 0.89802165 0.23052448]
 [0.94971341 0.71972517 0.43172997]]


[[0.95146236 0.76965661 0.89204403]
 [0.66373732 0.63776448 0.45653942]]
[[9 5 2]
 [9 2 1]
 [4 3 3]]


### 5. array_indexing_slicing

In [113]:
arra = np.random.randint(0,10,(3,3))
print("array matrixses : \n", arra)

print("\n")
arrays = np.array([[9,7,8],
 [7,6,5],
 [9,9 ,8]])

# slicing indexing
# rows
# syntax : array[row index]
print("row 0 print : ",arrays[0])  # ouput : row0 : [9,7,8]
print("Row 1 print",arrays[1])  # ouput : row1 : [7,6,5]
print("row 2 print : ",arrays[2])  # ouput : row2 : [9,9,8]
print("row 0 ki index 1 value : ",arrays[0,1])  # ouput : row0 : [7]
print("Negative slicing row ke last index ke index 2 ki value",arrays[-1,2]) # output : row2: [8]  negative silicing indexing
print("Row 2 ke index 2 ki value : ",arrays[2,2]) # output : row2: [8]
print("row2 ke all elements : ",arrays[2,0:3]) # output : row2: [9,9,8]
print("all values",arrays[:,1:3])
print("\n")

# cols
# syntax : array[row all :,col index]
print(arrays[:,0])  # ouput : col0 : [9,7,9]
print(arrays[:,1])  # ouput : col1:  [7,6,9]
print(arrays[:,2])  # ouput : col2 : [8,5,8]
print(arrays[:,-1]) # last element print
print(arrays[:,-1])


# problem : Maan lo tumhe upar wale array ki pehli do rows aur aakhri do columns chahiye.
print("sub array or matrixs : \n",arrays[0:2,0:2])
print("sub array 2 or matrixs : \n",arrays[1:3,1:3])
print("sub array 3 or matrixs : \n",arrays[:,0:2])

array matrixses : 
 [[8 6 9]
 [7 7 5]
 [8 1 6]]


row 0 print :  [9 7 8]
Row 1 print [7 6 5]
row 2 print :  [9 9 8]
row 0 ki index 1 value :  7
Negative slicing row ke last index ke index 2 ki value 8
Row 2 ke index 2 ki value :  8
row2 ke all elements :  [9 9 8]
all values [[7 8]
 [6 5]
 [9 8]]


[9 7 9]
[7 6 9]
[8 5 8]
[8 5 8]
[8 5 8]
sub array or matrixs : 
 [[9 7]
 [7 6]]
sub array 2 or matrixs : 
 [[6 5]
 [9 8]]
sub array 3 or matrixs : 
 [[9 7]
 [7 6]
 [9 9]]
