In [2]:
import numpy as np

In [7]:
orginal_array = np.arange(1,13)
print(orginal_array)

# reshape array
reshape = orginal_array.reshape(3,4)
print(reshape)

# auto col genarte
auto_reshaped = orginal_array.reshape(3,-1)
print(auto_reshaped)
print(auto_reshaped.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


### Revel()

In [ ]:
orginal_array = np.arange(1,17)
print("Orignal array : ", orginal_array)

## convert into reshape
reshape_array = orginal_array.reshape(4,-1)
print("resphe array and auto col: \n",reshape)


## iss reshpe array ko wapas array me convert karna hai
again_convert_into_orginal_array = reshape_array.ravel()
print("again convert into orginal array or 1d : ",again_convert_into_orginal_array)

## ravel() and flatten() is same 
## ravel() = orginal se link hota hai
## flatten() = copy banata hai 

## falting araay 
falting_array = reshape_array.flatten()
print("falten array : ",falting_array)





Orignal array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
resphe array and auto col: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
again convert into orginal array or 1d :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
falten array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


### Tranpose ( .T)

*row to col and col to row thats it*

In [27]:
orginal_array = np.arange(1,13)
print("orignal array : ",orginal_array)

## reshape this array into 3*4
reshape_array = orginal_array.reshape(3,4)
print("reshaped array : ",reshape_array)

print("array shpe after transpose : ",reshape_array.shape)


## trnaspose this array 
transpose = reshape_array.T
print("\n Transpose array: \n",transpose)
print("array shpe before transpose : ",transpose.shape)


orignal array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped array :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array shpe after transpose :  (3, 4)

 Transpose array: 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
array shpe before transpose :  (4, 3)


## Resize array

*Array ki size ko permamently change kar deta hai*

In [34]:
array = np.arange(1,6)
array.resize(4,4)
print(array)

[[1 2 3 4]
 [5 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
orginal_array = np.arange(20)
print(orginal_array)

reshaped_array = orginal_array.reshape(5,-1)
print(reshaped_array)
print(reshaped_array.shape)





[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [ ]:
array = np.arange(1,5).reshape(2,2)
print("array : ",array)
print(array.shape)
print(array.ndim)

ravel = array.ravel()
print("Ravel : \n",ravel)
ravel[2] = 20
print("value upade : ",ravel) ## value upade in ravle
print(array) ## orginal array me bhi value upade hua hai revel se


flatten_array = array.flatten()
print("faltten arrayy : ",flatten_array)
flatten_array[2] = 3
print("faltten value upade : ",flatten_array) 
print(array)

## faltten()
## faltten orignal array ka copy kar leta hai
## and value chnage karne per koi farqk nahi padta hai orginal array per

## ravel()
## orginal array ki value o deta hai
## yaha orginal array ko copy nahi karta hai
## and issme value upade karne per 
## orginal array me bhi upade ho jata hai




array :  [[1 2]
 [3 4]]
(2, 2)
2
Ravel : 
 [1 2 3 4]
value upade :  [ 1  2 20  4]
[[ 1  2]
 [20  4]]
faltten arrayy :  [ 1  2 20  4]
faltten value upade :  [1 2 3 4]
[[ 1  2]
 [20  4]]


In [68]:
original_array = np.arange(1,13)
print("orginal_array : ",orginal_array)

respahed_array = original_array.reshape(3,-1)
print(respahed_array)
print(respahed_array.shape)

print(respahed_array.T)
print(respahed_array.shape)


orginal_array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(3, 4)


In [71]:
aerray = np.arange(1,10)
aerray.resize(4,4)
print(aerray)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 0 0]
 [0 0 0 0]]
