### Numpy

In [2]:
import numpy as np
import time

### Creating array from list

In [ ]:

arr_1d = np.array([1,2,3,4,5])
print("1D array : ",arr_1d)


arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : ",arr_2d)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


### list vs numpy

In [13]:
py_list = [1,2,3,4]
print("python list : ",py_list)
print("python list multiplication: ",py_list * 2)


np_array = np.array([1,2,3,4])
print("numpy array multiplication : ",np_array * 2)



start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List opreation time : ", time.time() - start)

tart = time.time()
np_array = np.arange(1000000) * 2
print("\n numpy opreation time : ", time.time() - start)



python list :  [1, 2, 3, 4]
python list multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
numpy array multiplication :  [2 4 6 8]

 List opreation time :  0.17414212226867676

 numpy opreation time :  0.17414212226867676


### Creating array from startch

In [15]:



zeros = np.zeros((3,4))
print("zeros matrixs: \n",zeros)


ones = np.ones((2,3))
print("ones matrixs: \n",ones)


full = np.full((3,3),10)
print("full matrixs: \n",full)


random = np.random.random((4,5)) # random() ek class hai iske ander bahaut are method hai we write random.random((2,3))
# mtlb 2,3 mtlb jiten size ke matrix chaiye wo likhte hai
# random value hamesa 0 and 1 ke bich me hoti hai
print("randon matrixs: \n",random)


sequence = np.arange(0,10,2)
print("sequence array:\n",sequence)

zeros matrixs: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones matrixs: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full matrixs: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
randon matrixs: 
 [[0.29519287 0.12279669 0.469268   0.25032644 0.50704096]
 [0.14474093 0.60621739 0.54260997 0.34595478 0.92620434]
 [0.84646323 0.10780309 0.80559898 0.80778998 0.64309164]
 [0.74683501 0.30399684 0.67880946 0.34466026 0.17851768]]
sequence array:
 [0 2 4 6 8]


#### Vector, Matrix and Tensor

In [16]:
Vector = np.array([1,2,3,4])
print("Vector : ",Vector)

matrix = np.array([[1,2,3,4],
                   [5,6,7,8]])
print("matrix : ",matrix)


tensor = np.array([[[1,2,3,4],[5,6,7,8]],
                   [[9,1,2,3],[1,2,3,4]]])
print("tensor : ",tensor)

Vector :  [1 2 3 4]
matrix :  [[1 2 3 4]
 [5 6 7 8]]
tensor :  [[[1 2 3 4]
  [5 6 7 8]]

 [[9 1 2 3]
  [1 2 3 4]]]


### Array proprties

In [17]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
print("Shape : ",arr.shape)
print("Dimensonal : ",arr.ndim)
print("Size : ",arr.size)
print("Data type : ",arr.dtype)

Shape :  (2, 4)
Dimensonal :  2
Size :  8
Data type :  int64


### Array Reshaping

In [25]:



arr = np.arange(12)
print("Orignal array : ", arr)


reshaped = arr.reshape((3,4))
print("\n Reshaped array :\n", reshaped)

# yaha copy retrun karta hai 
flattened  = reshaped.flatten()
print("\n flattened array :", flattened)

# and yaha orginal value return karta hai
raveled = reshaped.ravel()
print("\n raveled array :", raveled)


transpose = reshaped.T
print("\nTranspose :\n",transpose)

Orignal array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
